import { SubjectInfo, TaskDifficulty, PriorityTag, UserSettings, Task, StudySession } from '../types';

export const SUBJECTS: Record<string, SubjectInfo> = {
  physics: {
    id: 'physics',
    name: 'Physics',
    shortCode: 'PHY',
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    badgeBg: 'bg-blue-500/15 text-blue-300 border-blue-500/30',
    accentHex: '#60a5fa',
    description: 'Mechanics, Electromagnetism, Quantum Physics & Optics',
    topicsSample: ['Classical Mechanics', 'Maxwell Equations', 'Thermodynamics', 'Quantum Mechanics', 'Wave Optics'],
  },
  chemistry: {
    id: 'chemistry',
    name: 'Chemistry',
    shortCode: 'CHEM',
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    badgeBg: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30',
    accentHex: '#34d399',
    description: 'Organic Mechanisms, Physical Chemistry & Inorganic bonding',
    topicsSample: ['Organic Reaction Mechanisms', 'Chemical Equilibrium', 'Electrochemistry', 'Coordination Compounds', 'Thermodynamics'],
  },
  mathematics: {
    id: 'mathematics',
    name: 'Mathematics',
    shortCode: 'MATH',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    badgeBg: 'bg-amber-500/15 text-amber-300 border-amber-500/30',
    accentHex: '#f59e0b',
    description: 'Calculus, Vectors, Linear Algebra & Differential Equations',
    topicsSample: ['Integral Calculus', 'Differential Equations', 'Complex Numbers', 'Vector Analysis', 'Matrix Algebra'],
  },
  general: {
    id: 'general',
    name: 'General STEM',
    shortCode: 'GEN',
    color: 'text-zinc-400',
    bgColor: 'bg-zinc-800/50',
    borderColor: 'border-zinc-700/50',
    badgeBg: 'bg-zinc-800/80 text-zinc-300 border-zinc-700/60',
    accentHex: '#a1a1aa',
    description: 'General study, review, and exam practice',
    topicsSample: ['Mock Exam Review', 'Formula Sheet Revision', 'Lab Reports'],
  }
};

export const DIFFICULTY_CONFIG: Record<TaskDifficulty, { label: string; color: string; bg: string; border: string }> = {
  easy: {
    label: 'Easy',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
  },
  medium: {
    label: 'Medium',
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/20',
  },
  hard: {
    label: 'Hard',
    color: 'text-rose-400',
    bg: 'bg-rose-500/10',
    border: 'border-rose-500/20',
  },
  olympiad: {
    label: 'JEE / Olympiad',
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/20',
  },
};

export const PRIORITY_CONFIG: Record<PriorityTag, { label: string; color: string; bg: string }> = {
  low: { label: 'Low', color: 'text-zinc-400', bg: 'bg-zinc-800/80' },
  medium: { label: 'Medium', color: 'text-amber-400', bg: 'bg-amber-950/60' },
  high: { label: 'High', color: 'text-orange-400', bg: 'bg-orange-950/60' },
  urgent: { label: 'Urgent', color: 'text-red-400', bg: 'bg-red-950/60' },
};

export const DEFAULT_SETTINGS: UserSettings = {
  dailyGoalMinutes: 240, // 4 hours
  pomodoroFocusMinutes: 25,
  pomodoroBreakMinutes: 5,
  pomodoroLongBreakMinutes: 15,
  autoStartNextCycle: false,
  soundEnabled: true,
  soundVolume: 0.7,
  syncVaultKey: `STEM-${Math.random().toString(36).substring(2, 8).toUpperCase()}`,
  autoCloudSync: false,
};

// Generate seed data for initial view so the user immediately sees charts and active tasks
const getTodayStr = () => new Date().toISOString().split('T')[0];

const getPastDateStr = (daysAgo: number) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
};

export const SEED_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Rotational Dynamics Problem Set & Inertia Derivations',
    description: 'Solve 15 advanced torque & angular momentum problems from Irodov / JEE Advanced set.',
    subject: 'physics',
    date: getTodayStr(),
    estimatedMinutes: 90,
    completedMinutes: 60,
    difficulty: 'olympiad',
    priority: 'urgent',
    status: 'in_progress',
    createdAt: getPastDateStr(1),
    subtasks: [
      { id: 'st-1', title: 'Derive moment of inertia for solid hemisphere', completed: true },
      { id: 'st-2', title: 'Solve rolling without slipping problems on inclined planes', completed: true },
      { id: 'st-3', title: 'Complete conservation of angular momentum collisions', completed: false },
    ],
  },
  {
    id: 'task-2',
    title: 'Electrophilic Aromatic Substitution Mechanisms',
    description: 'Review Nitration, Halogenation, Sulfonation & Friedel-Crafts alkylation reaction pathways.',
    subject: 'chemistry',
    date: getTodayStr(),
    estimatedMinutes: 60,
    completedMinutes: 45,
    difficulty: 'hard',
    priority: 'high',
    status: 'in_progress',
    createdAt: getPastDateStr(2),
    subtasks: [
      { id: 'st-4', title: 'Draw sigma complex resonance structures', completed: true },
      { id: 'st-5', title: 'Analyze ortho/para vs meta directing groups', completed: true },
      { id: 'st-6', title: 'Practice synthesis reactions for multi-step aromatic compounds', completed: false },
    ],
  },
  {
    id: 'task-3',
    title: 'Definite Integration & Reduction Formulae',
    description: 'Master Integration by parts, Wallis formula, and Leibnitz rule for differentiation under integral sign.',
    subject: 'mathematics',
    date: getTodayStr(),
    estimatedMinutes: 120,
    completedMinutes: 120,
    difficulty: 'hard',
    priority: 'high',
    status: 'completed',
    createdAt: getPastDateStr(3),
    completedAt: getTodayStr(),
    subtasks: [
      { id: 'st-7', title: 'Prove King property of integration', completed: true },
      { id: 'st-8', title: 'Solve 10 definite integral problems with periodic limits', completed: true },
      { id: 'st-9', title: 'Review Leibnitz integral theorem examples', completed: true },
    ],
  },
  {
    id: 'task-4',
    title: 'Maxwell Equations & Electromagnetic Wave Proofs',
    description: 'Derive wave equation from Ampere-Maxwell law in vacuum and dielectric media.',
    subject: 'physics',
    date: getPastDateStr(1),
    estimatedMinutes: 75,
    completedMinutes: 75,
    difficulty: 'hard',
    priority: 'medium',
    status: 'completed',
    createdAt: getPastDateStr(2),
    completedAt: getPastDateStr(1),
    subtasks: [
      { id: 'st-10', title: 'Calculate Poynting vector for EM wave', completed: true },
      { id: 'st-11', title: 'Derive speed of light c = 1/sqrt(mu0 * eps0)', completed: true },
    ],
  },
  {
    id: 'task-5',
    title: 'Thermodynamics & Gibbs Free Energy Problems',
    description: 'Work through enthalpy, entropy, and spontaneous process criteria in physical chemistry.',
    subject: 'chemistry',
    date: getPastDateStr(2),
    estimatedMinutes: 90,
    completedMinutes: 90,
    difficulty: 'medium',
    priority: 'high',
    status: 'completed',
    createdAt: getPastDateStr(4),
    completedAt: getPastDateStr(2),
    subtasks: [
      { id: 'st-12', title: 'Calculate ΔG° from equilibrium constant K', completed: true },
      { id: 'st-13', title: 'Solve Carnot cycle efficiency problems', completed: true },
    ],
  },
  {
    id: 'task-6',
    title: 'Differential Equations & Eigenvalue Problems',
    description: 'Solve second-order linear ODEs with constant coefficients and boundary conditions.',
    subject: 'mathematics',
    date: getTodayStr(),
    estimatedMinutes: 60,
    completedMinutes: 0,
    difficulty: 'medium',
    priority: 'medium',
    status: 'todo',
    createdAt: getTodayStr(),
    subtasks: [
      { id: 'st-14', title: 'Find characteristic roots for oscillatory system', completed: false },
      { id: 'st-15', title: 'Apply method of undetermined coefficients', completed: false },
    ],
  }
];

export const SEED_SESSIONS: StudySession[] = [
  {
    id: 'sess-1',
    subject: 'physics',
    mode: 'flowstate',
    durationMinutes: 60,
    secondsSpent: 3600,
    startTime: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    date: getTodayStr(),
    linkedTaskId: 'task-1',
    linkedTaskTitle: 'Rotational Dynamics Problem Set & Inertia Derivations',
    productivityRating: 5,
    notes: 'Deep focus on torque equations and rolling motion.',
  },
  {
    id: 'sess-2',
    subject: 'chemistry',
    mode: 'pomodoro',
    durationMinutes: 45,
    secondsSpent: 2700,
    startTime: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    date: getTodayStr(),
    linkedTaskId: 'task-2',
    linkedTaskTitle: 'Electrophilic Aromatic Substitution Mechanisms',
    productivityRating: 4,
    notes: 'Completed nitration and sulfonation pathways.',
  },
  {
    id: 'sess-3',
    subject: 'mathematics',
    mode: 'custom',
    durationMinutes: 120,
    secondsSpent: 7200,
    startTime: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    date: getPastDateStr(1),
    linkedTaskId: 'task-3',
    linkedTaskTitle: 'Definite Integration & Reduction Formulae',
    productivityRating: 5,
    notes: 'Solved 10 tough integration problems.',
  },
  {
    id: 'sess-4',
    subject: 'physics',
    mode: 'pomodoro',
    durationMinutes: 75,
    secondsSpent: 4500,
    startTime: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() - 27 * 3600 * 1000).toISOString(),
    date: getPastDateStr(1),
    linkedTaskId: 'task-4',
    linkedTaskTitle: 'Maxwell Equations & Electromagnetic Wave Proofs',
    productivityRating: 4,
  },
  {
    id: 'sess-5',
    subject: 'chemistry',
    mode: 'flowstate',
    durationMinutes: 90,
    secondsSpent: 5400,
    startTime: new Date(Date.now() - 52 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
    date: getPastDateStr(2),
    linkedTaskId: 'task-5',
    linkedTaskTitle: 'Thermodynamics & Gibbs Free Energy Problems',
    productivityRating: 5,
  },
  {
    id: 'sess-6',
    subject: 'mathematics',
    mode: 'pomodoro',
    durationMinutes: 110,
    secondsSpent: 6600,
    startTime: new Date(Date.now() - 76 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() - 74 * 3600 * 1000).toISOString(),
    date: getPastDateStr(3),
    productivityRating: 4,
  },
  {
    id: 'sess-7',
    subject: 'physics',
    mode: 'flowstate',
    durationMinutes: 130,
    secondsSpent: 7800,
    startTime: new Date(Date.now() - 100 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() - 98 * 3600 * 1000).toISOString(),
    date: getPastDateStr(4),
    productivityRating: 5,
  }
];
